### PR TITLE
Fix compile error in tsSLList.h

### PR DESCRIPTION
**Pull request by JJL772**
Fixes the following build error in `tsSLIterConst` with clang 19.
```
clang++  -D_GNU_SOURCE -D_DEFAULT_SOURCE          -D_X86_64_ -DUNIX  -Dlinux   -DBUILDING_libCom_API   -O3 -g   -Wall      -mtune=generic     -m64  -fPIC -I. -I../O.Common -I. -I../osi/compiler/clang -I../osi/compiler/default -I. -I../osi/os/Linux -I../osi/os/posix -I../osi/os/default -I.. -I../as -I../bucketLib -I../calc -I../cvtFast -I../cppStd -I../cxxTemplates -I../dbmf -I../ellLib -I../env -I../error -I../fdmgr -I../flex -I../freeList -I../gpHash -I../iocsh -I../log -I../macLib -I../misc -I../osi -I../pool -I../ring -I../taskwd -I../timer -I../yacc -I../yacc -I../yajl -I../../../../include/compiler/clang -I../../../../include/os/Linux -I../../../../include         -c ../cxxTemplates/resourceLib.cpp
In file included from ../cxxTemplates/resourceLib.cpp:15:
In file included from ../cxxTemplates/resourceLib.h:43:
../cxxTemplates/tsSLList.h:314:32: error: no member named 'pConstEntry' in 'tsSLIterConst<T>'
  314 |     return this->pEntry == rhs.pConstEntry;
      |                            ~~~ ^
../cxxTemplates/tsSLList.h:320:32: error: no member named 'pConstEntry' in 'tsSLIterConst<T>'
  320 |     return this->pEntry != rhs.pConstEntry;
      |                            ~~~ ^
2 errors generated.
```

Seems to have been introduced in 3fb814777176e1d09e82684564f6926ad2689e8e way back in 2001. Not sure why clang is all of a sudden evaluating that operator.

### CODE REVIEW

**Comment by simon-ess** [comment]
For anyone who stumbles upon this later, it seems that clang19 has become more strict about this sort of issue, see https://releases.llvm.org/19.1.0/tools/clang/docs/ReleaseNotes.html. In particular:

> Clang now looks up members of the current instantiation in the template definition context if the current instantiation has no dependent base classes.

with the example given as
```
template<typename T>
struct A {
  int f() {
    return this->x; // error: no member named 'x' in 'A<T>'
  }
};
```
